# Generated by Django 4.2.12 on 2024-05-10 09:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('applies', '0008_alter_competitivecourseapplied_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='competitivecourseapplied',
            name='course',
        ),
        migrations.RemoveField(
            model_name='competitivecourseapplied',
            name='user',
        ),
        migrations.RemoveField(
            model_name='foreignlanguageapplied',
            name='languages',
        ),
        migrations.RemoveField(
            model_name='foreignlanguageapplied',
            name='user',
        ),
        migrations.DeleteModel(
            name='CompetitiveCourse',
        ),
        migrations.DeleteModel(
            name='CompetitiveCourseApplied',
        ),
        migrations.DeleteModel(
            name='ForeignLanguage',
        ),
        migrations.DeleteModel(
            name='ForeignLanguageApplied',
        ),
    ]
