# Generated by Django 4.2.12 on 2024-05-10 11:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_video_thumbnail'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Video',
        ),
    ]
